### PR TITLE
Adding proxy table creation script

### PR DESCRIPTION
**Pull request by moy8011**
Adding proxy table creation script and updating hdfs_setup.sh with proxy as a source

### CODE REVIEW

**Comment by natedogs911** [comment]
LGTM

**Comment by daortizh** [comment]
LGTM

**Comment by NathanSegerlind** [comment]
I'll have to do a quick change to the proxy code to get it consistent with this

**Comment by rabarona** [comment]
@moy8011 please revert this code from 1.0.1 and push to dev branch. Thanks.

**Pull request merged**
